name: Sync labels
on:
    workflow_dispatch: {}
    # Disabled for now while we're testing
    # push:
    #     branches:
    #         - develop
    #     paths:
    #         - .github/labels.yml
jobs:
    sync-labels:
        uses: vector-im/element-meta/.github/workflows/sync-labels.yml@develop
        with:
            LABELS: |
                vector-im/element-meta
                .github/labels.yml
            DELETE: true
            WET: true
        secrets:
            ELEMENT_BOT_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
